server:
  port: ${CUSTOMER_SERVICE_PORT:8284}
  forward-headers-strategy: framework

#-----------------------------------------
spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: ${CUSTOMER_SERVICE_NAME:customer-service}
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bmt}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
      # hibernate.jdbc.lob.non_contextual_creation: false

#-----------------------------------------

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

#-----------------------------------------

eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_HOSTNAME}:${SERVICE_DISCOVERY_PORT}/eureka/
  instance:
    hostname: ${SERVICE_DISCOVERY_HOSTNAME:localhost}
    prefer-ip-address: true


#-----------------------------------------
management:
  endpoint:
    health:
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - info
#-----------------------------------------

logging:
  level:
    root: info
    org:
      springframework:
        cache: trace
    io:
      gnt:
        bmt: info

#-----------------------------------------
